---
# Source: spark-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-spark-operator
  namespace: spark-operator
  labels:
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/instance: spark
    app.kubernetes.io/version: "v1beta2-1.2.0-3.0.0"



